apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aegis-redis-mvp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 19.0.0
      helm:
        valueFiles:
          - $values/kubernetes/envs/mvp/infrastructure/redis/values.yaml
    - repoURL: https://github.com/Aegis-AI-Organizations/Aegis-AI-Infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: aegis-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
