global:
  imageRegistry: public.ecr.aws
  storageClass: "standard" # Adjust based on cloud provider

auth:
  existingSecret: "aegis-env"
  rootUserKey: "MINIO_ROOT_USER"
  rootPasswordKey: "MINIO_ROOT_PASSWORD"

persistence:
  enabled: true
  size: 10Gi

defaultBuckets: "aegis-telemetry"

service:
  type: ClusterIP
  ports:
    api: 9000
    console: 9001

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
