apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: defaults-postgres
  namespace: aegis-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: aegis-postgres-mvp
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: api-gateway-mvp
        - matchLabels:
            app: brain-mvp
        - matchLabels:
            app.kubernetes.io/name: temporal
            app.kubernetes.io/instance: aegis-temporal-mvp
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
