apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: defaults-temporal
  namespace: aegis-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: temporal
      app.kubernetes.io/instance: aegis-temporal-mvp
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: api-gateway-mvp
        - matchLabels:
            app: brain-mvp
        - matchLabels:
            app: pentest-worker-mvp
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": keda
      toPorts:
        - ports:
            - port: "7233"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: postgresql
            app.kubernetes.io/instance: aegis-postgres-mvp
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
