global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/clickhouse
  tag: 25.3.2-debian-12-r3

shards: 1
replicaCount: 1

keeper:
  enabled: false

auth:
  username: aegis_admin
  existingSecret: "aegis-env"
  existingSecretKey: "CLICKHOUSE_PASSWORD"

persistence:
  enabled: true
  size: 8Gi
