apiVersion: v1
kind: ConfigMap
metadata:
  name: aegis-edge-proxy-config
  namespace: aegis-system
  labels:
    app.kubernetes.io/name: aegis-edge-proxy
    app.kubernetes.io/part-of: aegis
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 80;
        server_name www.aegis-ai.fr;

        return 301 https://aegis-ai.fr$request_uri;
      }

      server {
        listen 80;
        server_name api.aegis-ai.fr;

        location / {
          proxy_pass http://api-gateway-mvp:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
        }
      }

      server {
        listen 80;
        server_name storage.aegis-ai.fr;

        location / {
          proxy_pass http://aegis-minio-mvp:9000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
      }

      server {
        listen 80;
        server_name console-storage.aegis-ai.fr;

        location / {
          proxy_pass http://aegis-minio-mvp:9001;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
      }

      server {
        listen 80;
        server_name aegis-ai.fr;

        location / {
          proxy_pass http://landing-mvp:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
        }
      }

      server {
        listen 80;
        server_name app.aegis-ai.fr;

        location / {
          proxy_pass http://dashboard-mvp:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
        }
      }

      server {
        listen 80 default_server;
        return 404;
      }
    }
