apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - edge-proxy-configmap.yaml
  - edge-proxy-deployment.yaml
  - edge-proxy-service.yaml
  - deployment.yaml
