prometheus:
  enabled: false
grafana:
  enabled: false
cassandra:
  enabled: false
postgresql:
  enabled: false
elasticsearch:
  enabled: false

server:
  replicaCount: 1
  config:
    persistence:
      # On définit quelles clés dans 'datastores' utiliser
      defaultStore: persistence
      visibilityStore: visibility
      numHistoryShards: 512
      datastores:
        persistence:
          sql:
            createDatabase: true
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: aegis_persistence
            connectAddr: "aegis-postgres-mvp-postgresql:5432"
            connectProtocol: tcp
            user: aegis_admin
            existingSecret: aegis-env
            secretKey: POSTGRES_PASSWORD
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"
        visibility:
          sql:
            createDatabase: true
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: aegis_visibility
            connectAddr: "aegis-postgres-mvp-postgresql:5432"
            connectProtocol: tcp
            user: aegis_admin
            existingSecret: aegis-env
            secretKey: POSTGRES_PASSWORD
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"
