apiVersion: v1
kind: Service
metadata:
  name: aegis-target
  namespace: aegis-local-target
  labels:
    app.kubernetes.io/name: aegis-target
    app.kubernetes.io/part-of: aegis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aegis-target
  ports:
    - name: http
      port: 8080
      targetPort: http
