apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-system

resources:
  - job.yaml

configMapGenerator:
  - name: aegis-db-init-sql
    files:
      - init.sql

generatorOptions:
  disableNameSuffixHash: true
