apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aegis-issuers-mvp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Aegis-AI-Organizations/Aegis-AI-Infra.git
    targetRevision: main
    path: kubernetes/envs/mvp/infrastructure/cert-manager/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
