apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure/keda/application.yaml
  - api-gateway/application.yaml
  - brain/application.yaml
  - dashboard/application.yaml
  - infrastructure/db-init/application.yaml
  - infrastructure/postgres/application.yaml
  - infrastructure/temporal/application.yaml
  - network-policies/application.yaml
  - pentest-worker
