apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure/cert-manager/application.yaml
  - infrastructure/cert-manager/issuers-app.yaml
  - infrastructure/keda/application.yaml
  - api-gateway/application.yaml
  - brain/application.yaml
  - dashboard/application.yaml
  - dashboard/config-application.yaml
  - infrastructure/db-init/application.yaml
  - infrastructure/postgres/application.yaml
  - infrastructure/temporal/application.yaml
  - infrastructure/minio/application.yaml
  - infrastructure/redis/application.yaml
  - network-policies/application.yaml
  - pentest-worker/application.yaml
