apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-system

resources:
  - job.yaml

configMapGenerator:
  - name: aegis-neo4j-schema
    files:
      - schema.cypher

generatorOptions:
  disableNameSuffixHash: true
