apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aegis-postgres-mvp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.15
    helm:
      valuesObject:
        global:
          imageRegistry: public.ecr.aws
          postgresql:
            auth:
              existingSecret: "aegis-env"
              secretKeys:
                adminPasswordKey: "POSTGRES_PASSWORD"
                userPasswordKey: "POSTGRES_PASSWORD"
              database: "aegis_db"
              username: "aegis_admin"
        image:
          registry: public.ecr.aws
          repository: bitnami/postgresql
          tag: 16.2.0
        primary:
          image:
            registry: public.ecr.aws
            repository: bitnami/postgresql
            tag: 16.2.0
          configuration: |-
            listen_addresses = '*'
            max_connections = 300
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          initdb:
            scripts:
              init-databases.sql: |
                CREATE DATABASE aegis_persistence;
                CREATE DATABASE aegis_visibility;
          persistence:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: aegis-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
